int32 month         # start month of the interval
int32 day           # start day of the interval
int32 hour          # start hour of the interval
int32 minute        # start minute of the interval
duration duration   # time interval duration for the poisson
float32 shape       # alpha of gamma distribution 
float32 scale       # beta  of gamma distribution
float32 rate        # point in gamma distribution for the poisson rate
