# Region: WayPoint
"1": "WayPoint1"
"2": "WayPoint2"
"3": "WayPoint3"
"5": "WayPoint5"
"6": "WayPoint6"
"7": "WayPoint7"
"8": "WayPoint8"
"9": "WayPoint9"
"10": "WayPoint10"
"11": "WayPoint11"
"12": "WayPoint12"
"13": "WayPoint13"

# "134": ["KitchenTableLow", "KitchenTableHigh"]
