# Region: WayPoint
"1": "WayPoint17"
"2": "WayPoint18"
"3": "WayPoint19"
"4": "WayPoint20"
"5": "WayPoint21"
"6": "Station"
"7": "WayPoint22"
"8": "WayPoint3"
"9": "WayPoint3"
"10": "WayPoint10"

# "134": ["KitchenTableLow", "KitchenTableHigh"]
